package gov.ravec.backend.dto;



public enum RoleDto {
	
	 ABS,
     CHILD,
     FATHER,
     MOTHER,
     DECLARANT,
     DECEASED,
     SPOUSE_1,
     SPOUSE_2,
     DECLARANT_1,
     DECLARANT_2,
    WITNESS_1,
    WITNESS_2,
    REQUERANT,
	
	
	
	
	/**
	 * ABS
ADDED_ABS
ADDED_ADOPTIVE_COPARENT
ADDED_ADOPTIVE_FATHER
ADDED_ADOPTIVE_MOTHER
ADDED_CHILD
ADDED_CONCERNED_PERSON
ADDED_COPARENT
ADDED_COPARENT_THAT_HAS_MADE_A_PRENATAL_RECOGNITION
ADDED_DECEASED
ADDED_DECLARANT
ADDED_DECLARANT_1
ADDED_DECLARANT_2
ADDED_FATHER
ADDED_FATHER_THAT_HAS_MADE_A_PRENATAL_RECOGNITION
ADDED_LEGAL_REPRESENTATIVE
ADDED_MISSING
ADDED_MOTHER
ADDED_NOT_RECOGNISING_COPARENT
ADDED_NOT_RECOGNISING_FATHER
ADDED_RECOGNIZER_COPARENT
ADDED_RECOGNIZER_FATHER
ADDED_RECOGNIZER_MOTHER
ADDED_SPOUSE_1
ADDED_SPOUSE_2
ADDED_WITNESS
ADOPTIVE_COPARENT
ADOPTIVE_FATHER
ADOPTIVE_MOTHER
CHILD
CONCERNED_PERSON
COPARENT
COPARENT_THAT_HAS_MADE_A_PRENATAL_RECOGNITION
DECEASED
DECLARANT
DECLARANT_1
DECLARANT_2
DOCTER
FATHER
FATHER_SPOUSE_1
FATHER_SPOUSE_2
FATHER_THAT_HAS_MADE_A_PRENATAL_RECOGNITION
LEGAL_REPRESENTATIVE
MIDWIFE
MISSING
MOTHER
MOTHER_SPOUSE_1
MOTHER_SPOUSE_2
NOT_RECOGNISING_COPARENT
NOT_RECOGNISING_FATHER
OTHER
PARENT
RECOGNIZER_COPARENT
RECOGNIZER_FATHER
RECOGNIZER_MOTHER
REMOVED_ABS
REMOVED_ADOPTIVE_COPARENT
REMOVED_ADOPTIVE_FATHER
REMOVED_ADOPTIVE_MOTHER
REMOVED_CHILD
REMOVED_CONCERNED_PERSON
REMOVED_COPARENT
REMOVED_COPARENT_THAT_HAS_MADE_A_PRENATAL_RECOGNITION
REMOVED_DECEASED
REMOVED_DECLARANT
REMOVED_DECLARANT_1
REMOVED_DECLARANT_2
REMOVED_FATHER
REMOVED_FATHER_THAT_HAS_MADE_A_PRENATAL_RECOGNITION
REMOVED_LEGAL_REPRESENTATIVE
REMOVED_MISSING
REMOVED_MOTHER
REMOVED_NOT_RECOGNISING_COPARENT
REMOVED_NOT_RECOGNISING_FATHER
REMOVED_RECOGNIZER_COPARENT
REMOVED_RECOGNIZER_FATHER
REMOVED_RECOGNIZER_MOTHER
REMOVED_SPOUSE_1
REMOVED_SPOUSE_2
REMOVED_WITNESS
SPOUSE_1
SPOUSE_2
WITNESS_1
WITNESS_2
	 */

}
