import { Component, inject } from '@angular/core';
import { Router } from '@angular/router';
import { MatDialog } from '@angular/material/dialog';
import { AuthService } from '../services/auth.service';
import { ActeSelectionDialogComponent, ActeSelectionResult } from './acte-selection-dialog/acte-selection-dialog.component';

export const COMMUNES_GUINEE: string[] = [
  'ALBADARIAH',
  'ALLASSOYAH',
  'ARFAMOUSSAYA',
  'BABILA',
  'BADY',
  'BAGUINET',
  'BAGUINY',
  'BALANDOU',
  'BALANDOUGOUBA',
  'BALAKI',
  'BALATO',
  'BALAYA (FARANAH)',
  'BALAYA (LELOUMA)',
  'BALIZIA',
  'BAMBAYA',
  'BAMKON',
  'BANIAN',
  'BANIÉ',
  'BANANKORO',
  'BANFÈLÈ',
  'BANKO',
  'BANORA',
  'BANTOUN',
  'BANTIGNEL',
  'BARDOU',
  'BARO',
  'BATÈ-NAFADJI',
  'BEINDOU (FARANAH)',
  'BEINDOU (KISSIDOUGOU)',
  'BENTY',
  'BEYLA (COMMUNE URBAINE)',
  'BHÊTA',
  'BIGNAMOU',
  'BINIKALA',
  'BINTIMODIA',
  'BISSIKIRIMA',
  'BODIÉ',
  'BOFFA (COMMUNE URBAINE)',
  'BOFOSSOU',
  'BOKÉ (COMMUNE URBAINE)',
  'BOLODOU',
  'BOOLA',
  'BOSSOU',
  'BOULA',
  'BOULLIWEL',
  'BOUROUWAL',
  'BOUROUWAL-TAPPÉ',
  'BOWÉ',
  'BOUNOUMA',
  'CISSÉLA',
  'COYAH (COMMUNE URBAINE)',
  'DABISS',
  'DABOLA (COMMUNE URBAINE)',
  'DALABA (COMMUNE URBAINE)',
  'DALEIN',
  'DAMANKANIA',
  'DAMARO',
  'DARALABÉ',
  'DARAMAGNAKI',
  'DANTILIA',
  'DARO',
  'DIDI',
  'DIALAKORO (DINGUIRAYE)',
  'DIALAKORO (MANDIANA)',
  'DIARAGUERELA',
  'DIASSODOU',
  'DIARI',
  'DIÉCKÉ',
  'DINGUIRAYE (COMMUNE URBAINE)',
  'DIOMABANA',
  'DIONFO',
  'DIONTOU',
  'DITINN',
  'DIXINN',
  'DJÉLIBAKORO',
  'DJIMBALA',
  'DOKO',
  'DOGOMET',
  'DONGOL TOUMA',
  'DONGHOL-SIGON',
  'DOUAKO',
  'DOUNET',
  'DOUGOUNTOUNI',
  'DOURA',
  'DOUPROU',
  'DUBRÉKA (COMMUNE URBAINE)',
  'FADOUSSABA',
  'FALESSADÉ',
  'FANGAMADOU',
  'FARALAKO',
  'FARMOREAH',
  'FARANAH (COMMUNE URBAINE)',
  'FASSANKONI',
  'FATAKO',
  'FELLO-KOUNDOUA',
  'FERMESSADOU',
  'FIDAKO',
  'FIRAWA',
  'FODÉCARIAH BALIMANA',
  'FONODOU',
  'FORÉCARIAH (COMMUNE URBAINE)',
  'FOUALAH',
  'FOUMBADOU',
  'FOUGOU',
  'FRANWALIA',
  'FRIA (COMMUNE URBAINE)',
  'FRIGUIAGBÉ',
  'GADHA WOUNDOU',
  'GAGNAKALY',
  'GAMA-BEREMA',
  'GARAMBE',
  'GAOUAL (COMMUNE URBAINE)',
  'GBACKÉDOU',
  'GBANGBADOU',
  'GBÉRÉDOU-BARANAMA',
  'GBÉSSIA',
  'GBÉSSOBA',
  'GONGORET (MAMOU)',
  'GONGORET (PITA)',
  'GOUÉCKÉ',
  'GOUGOUDJÈ',
  'GUÉASSO',
  'GUÉCKÉDOU (COMMUNE URBAINE)',
  'GUELO-N\'FALY',
  'GUENDEMBOU',
  'GUINGAN',
  'HAFIA',
  'HÈRÈMAKONO',
  'HÉRICO',
  'HIDAYATOU',
  'KAABAN',
  'KAALA',
  'KABACK',
  'KAGBÉLEN',
  'KAKONY',
  'KAKOSSA',
  'KALIAH',
  'KALINKO',
  'KALOUM',
  'KAMABY',
  'KAMSAR',
  'KANFARANDÉ',
  'KANKAMA',
  'KANKAN (COMMUNE URBAINE)',
  'KANKALABÉ',
  'KANSANGUI',
  'KANSEREAH',
  'KANTOUMANINA',
  'KARIFAMOREAH',
  'KARALA',
  'KASSA',
  'KASSADOU',
  'KAWESSI',
  'KÉBALY',
  'KÉROUANÉ (COMMUNE URBAINE)',
  'KHORIRA',
  'KIGNÉKO',
  'KINDOYE',
  'KINDIA (COMMUNE URBAINE)',
  'KINIÉBAKOURA',
  'KINIÉRAN',
  'KINIÉRO',
  'KISSIDOUGOU (COMMUNE URBAINE)',
  'KOBA (BOFFA)',
  'KOBA (DALABA)',
  'KOBA (TÉLIMÉLÉ)',
  'KOBÉLA',
  'KOBIKORO',
  'KODIARAN',
  'KOIN',
  'KOKOTA',
  'KOLABOUI',
  'KOLENTÉ',
  'KOLLANGUI',
  'KOLLET (TOUGUÉ)',
  'KOLLET (TÉLIMÉLÉ)',
  'KOLIA',
  'KOMODOU',
  'KOMOLAKOURA',
  'KONAH',
  'KONDÉADOU',
  'KONDIADOU',
  'KONDIANAKORO',
  'KONDIMBADOU',
  'KONINDOU',
  'KONSOTAMI',
  'KONKOURÉ',
  'KOROPARA',
  'KORBÈ',
  'KOSSANKORO',
  'KOUANKAN',
  'KOUBIA (COMMUNE URBAINE)',
  'KOUMBAN',
  'KOUMANDOU',
  'KOUMANA',
  'KOUMANDJAMBOUGOU',
  'KOUMBIA',
  'KOUNDARA (COMMUNE URBAINE)',
  'KOUNDIAN',
  'KOUNDOU',
  'KOUNSITEL',
  'KOURAMANGUI',
  'KOURIAH',
  'KOURATONGO',
  'KOUREMALÉ',
  'KOUROUSSA (COMMUNE URBAINE)',
  'KOUROUKORO',
  'KOYAMAH',
  'KOULÉ',
  'LABÉ (COMMUNE URBAINE)',
  'LAFOU',
  'LAINÉ',
  'LAMBANYI',
  'LANSANAYA',
  'LÉBÉKÉRÉ',
  'LÉLOUMA (COMMUNE URBAINE)',
  'LEY-MIRO',
  'LINKO',
  'LINSAN-SARAN',
  'LINSSAN',
  'LISSO',
  'LOLA (COMMUNE URBAINE)',
  'MACENTA (COMMUNE URBAINE)',
  'MACI',
  'MADINA-OULA',
  'MADINA-SALAMBANDE',
  'MADINA-WORA',
  'MAFERINYAH',
  'MALANTA',
  'MALAPOUYA',
  'MALÉAH',
  'MALI (COMMUNE URBAINE)',
  'MAMBIA',
  'MAMOU (COMMUNE URBAINE)',
  'MAMOUROUDOU',
  'MANFRAN',
  'MANDIANA (COMMUNE URBAINE)',
  'MANDA-SARAN',
  'MANEAH',
  'MANKOUNTAN',
  'MARELA',
  'MATAKAOU',
  'MATAM',
  'MATOTO',
  'MIGNADA',
  'MISSAMANA',
  'MISSIRA (KOUBIA)',
  'MISSIRA (TÉLIMÉLÉ)',
  'MOLOTA',
  'MOMBEYA',
  'MORIBAYA',
  'MORIBAYAH',
  'MORODOU',
  'MOUSSADOU',
  'MOUSSAYAH',
  'MYTTY',
  'N\'DÉMA',
  'N\'ZOO',
  'N\'ZÉBÉLA',
  'N\'ZÉRÉKORÉ (COMMUNE URBAINE)',
  'NABOUN',
  'NIAGARA',
  'NIAGASSOLA',
  'NIALIA',
  'NIANDANKORO',
  'NIANTANINA',
  'NINGUÉLANDÉ',
  'NIONSOMORIDOU',
  'NORASSOBA',
  'NOUNKOUNKAN',
  'NOUSSY',
  'NONGOA',
  'OUASSOU',
  'OUÉNDÉ-KÈNÈMA',
  'OURÉ-KABA',
  'ORÉMAI',
  'PALÉ',
  'PANZIAZOU',
  'PARAWOL',
  'PASSAYAH',
  'PÉLA',
  'PILLIMINI',
  'PITA (COMMUNE URBAINE)',
  'POPODARA',
  'PORÉDAKA',
  'RATOMA',
  'SABADOU-BARANAMA',
  'SAGALÉ',
  'SALADOU',
  'SAMANA',
  'SAMAYAH',
  'SAMBAÏLO',
  'SAMOÉ',
  'SANDÉNIA',
  'SANGARDO',
  'SANGARÉDI',
  'SANGUIANA',
  'SANGAREAH',
  'SANNÉ',
  'SANSALÉ',
  'SANSANDO',
  'SANOYAH',
  'SANTOU',
  'SANNOU',
  'SAREBOÏDO',
  'SARÉKALY',
  'SARAMOUSSAYA',
  'SAMAYA',
  'SELOUMA',
  'SENGBEDOU',
  'SÉRÉDOU',
  'SIKHOUROU',
  'SIGUIRI (COMMUNE URBAINE)',
  'SIGUIRINI',
  'SIBIRIBARO',
  'SINTALY',
  'SINTA',
  'SINKO',
  'SOGOLON',
  'SOKOURALA',
  'SONGOYAH',
  'SONFONIA',
  'SOROMAYA',
  'SOULOUTA',
  'SOYAH',
  'TANGALY',
  'TAMITA',
  'TANÈNÈ (BOKÉ)',
  'TANÈNÈ (DUBRÉKA)',
  'TARAMBALY',
  'TARIHOYE',
  'TÉGUÉRÉYAH',
  'TÉLIRÉ',
  'TÉKOULO',
  'TÉLIMÉLÉ (COMMUNE URBAINE)',
  'TEMESSADOU',
  'TERMESSÈ',
  'THIANGUEL-BORI',
  'THIÉWA',
  'THIONTHIAN',
  'TIMBI TOUNNI',
  'TIMBI-MADINA',
  'TIMBO',
  'TINDO',
  'TINTIOULÉN',
  'TIRO',
  'TOKOUNOU',
  'TOLO',
  'TOMBA KANSSA',
  'TOMBOLIA',
  'TOMBONI',
  'TONDON',
  'TORMÈLIN',
  'TOUBA (GAOUAL)',
  'TOUBA (MALI)',
  'TOUGUÉ (COMMUNE URBAINE)',
  'TOUGNIFILY',
  'TOUNTOUROUN',
  'VASSEREDOU',
  'WATTANKA',
  'WEND M\'BUR',
  'WOMEY',
  'WONKIFONG',
  'YÉLENZOU',
  'YEMBÈRING',
  'YENDÈ MILLIMOU',
  'YOMBIRO',
  'YOMOU (COMMUNE URBAINE)',
  'YOUKOUNKOUN',
];

const VOYELLES = 'AEIOUÉÈÊÀÂÎÏÔÙÛÜ';

function labelCommune(name: string): string {
  return VOYELLES.includes(name.charAt(0).toUpperCase())
    ? `Centre Principal d'${name}`
    : `Centre Principal de ${name}`;
}

@Component({
  selector: 'app-actes-home',
  templateUrl: './actes-home.component.html',
  styleUrls: ['./actes-home.component.css'],
})
export class ActesHomeComponent {

  private readonly router  = inject(Router);
  private readonly dialog  = inject(MatDialog);
  readonly authService     = inject(AuthService);

  readonly communes     = COMMUNES_GUINEE;
  readonly labelCommune = labelCommune;

  // Recherche simple (critères locaux — la recherche avancée est sur /admin/actes/listes)
  searchCommune   = '';
  searchNpi       = '';
  searchNom       = '';
  searchPrenom    = '';
  searchDateDebut = '';
  searchDateFin   = '';
  searchNumero    = '';
  searchTypeActe  = '';

  today = new Date();

  navigateToMariage(): void {
    this.router.navigate(['/admin/actes-mariage/creation']);
  }

  openCreationDialog(type: 'naissance' | 'deces' | 'autres'): void {
    const ref = this.dialog.open(ActeSelectionDialogComponent, {
      width: '960px',
      maxWidth: '96vw',
      data: { type },
      panelClass: 'acte-selection-panel',
    });
    ref.afterClosed().subscribe((result: ActeSelectionResult | undefined) => {
      if (result?.route) {
        this.router.navigate([result.route], result.queryParams ? { queryParams: result.queryParams } : {});
      }
    });
  }

  rechercher(): void {
    this.router.navigate(['/admin/actes/listes'], {
      queryParams: {
        commune:   this.searchCommune   || undefined,
        nom:       this.searchNom       || undefined,
        prenom:    this.searchPrenom    || undefined,
        npi:       this.searchNpi       || undefined,
        numero:    this.searchNumero    || undefined,
        typeActe:  this.searchTypeActe  || undefined,
        dateDebut: this.searchDateDebut || undefined,
        dateFin:   this.searchDateFin   || undefined,
      },
    });
  }

  effacerCriteres(): void {
    this.searchCommune   = '';
    this.searchNpi       = '';
    this.searchNom       = '';
    this.searchPrenom    = '';
    this.searchDateDebut = '';
    this.searchDateFin   = '';
    this.searchNumero    = '';
    this.searchTypeActe  = '';
  }
}
